<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common.props"></Import>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>PionereeDemo</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Abp.Web.Common" Version="11.1.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PionereeDemo.Core.Shared\PionereeDemo.Core.Shared.csproj" />
  </ItemGroup>
</Project>